# Generated by Django 3.0.6 on 2020-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CueApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue_type', models.CharField(max_length=60)),
                ('cue_number', models.IntegerField()),
            ],
        ),
    ]
