# Generated by Django 3.0.6 on 2020-06-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CueApp', '0002_cue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press_cue_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Press_cue_B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Press_cue_C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue_type', models.CharField(max_length=60)),
            ],
        ),
    ]
