# Generated by Django 3.0.6 on 2020-06-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CueApp', '0003_press_cue_a_press_cue_b_press_cue_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Cue_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue_type', models.CharField(max_length=60)),
                ('cue_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Current_Cue_B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue_type', models.CharField(max_length=60)),
                ('cue_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Current_Cue_C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue_type', models.CharField(max_length=60)),
                ('cue_number', models.IntegerField()),
            ],
        ),
    ]
